apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: z2b1s1uwt-go 
  janus-idp.io/tekton: z2b1s1uwt-go
  backstage.io/kubernetes-id: z2b1s1uwt-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z2b1s1uwt-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml