apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: z2b1s1uwt-go-gitops
  description: This is GitOps manifest for z2b1s1uwt-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=z2b1s1uwt-go
    backstage.io/kubernetes-id: z2b1s1uwt-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: z2b1s1uwt-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:z2b1s1uwt-go
